import Head from 'next/head'
import { Inter } from '@next/font/google'
import MainComp from './components/MainComp'
import MainContent from './components/MainContent'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>


      <Head>
        <title>Zachary Pagliaro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
      <MainContent />
      <div className="formWrapper">
        <div className="contactForm">
          
          
        </div>
      </div>
    </div>
    <MainComp />  
      
    </>
  )
}
